language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t eljoelee/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true eljoelee/react-test-app npm run test

after_success:
  - docker build -t eljoelee/docker-frontend ./frontend
  - docker build -t eljoelee/docker-backend ./backend
  - docker build -t eljoelee/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push eljoelee/docker-frontend
  - docker push eljoelee/docker-backend
  - docker push eljoelee/docker-nginx